name: Ministries Frontend CI/CD Setup

on:
  push:
    branches:
      - main  # Ensure this matches your branch where you push updates
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2

      # Set up SSH to execute commands on the remote server
      - name: Execute remote SSH commands
        run: |
          cd frontends/ministry  # Ensure this path matches your repo structure
          npm ci
          npm run build

      # Deploy built files to the remote server using SCP
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: "63.250.32.131"
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/eportal/web/enugustate.gov.ng/public_html/frontends/ministry
            git pull origin main  # Pull the latest changes from the repository
            npm install  # Install dependencies
            npm run build  # Build the project
            cp -r dist/* /home/eportal/web/enugustate.gov.ng/public_html/public/ministry/  # Copy the built files to the public directory
