   name: Ministries Frontend CI/CD Setup

   on:
     push:
       paths:
         - '/home/eportal/web/staging.enugustate.gov.ng/public_html/frontend/ministry/**'
     workflow_dispatch:

   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Use Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '20'
         - run: |
             cd /home/eportal/web/staging.enugustate.gov.ng/public_html/frontend/ministry
             npm ci
             npm run build
         - name: Deploy to Server
           uses: appleboy/scp-action@master
           with:
             host: "63.250.32.131"
             username: ${{ secrets.SSH_USERNAME }}
             password: ${{ secrets.SSH_PASSWORD }}
             source: "/home/eportal/web/staging.enugustate.gov.ng/public_html/frontend/ministry/dist/*"
             target: "/home/eportal/web/staging.enugustate.gov.ng/public_html/public/ministry"
